export const GET_FANTS_REQUEST = 'GET_FANTS_REQUEST'
export const GET_FANTS_SUCCESS = 'GET_FANTS_SUCCESS'
export const GET_FANTS_ERROR = 'GET_FANTS_ERROR'

export const FORM_DECK = 'FORM_DECK'
export const PLAY_FANT = 'PLAY_FANT'
export const RETURN_FANT = 'RETURN_FANT'
